// PHASE: NAME & DESCRIPTIOn
// AVAILABILITY: COLOR NAME & DESCRIPTION
// INTEGRITY: COLOR NAME & DESCRIPTION
// STATUS: OPEN, PENDING, INPROGRESS, CLOSE, APPROVE
// INITIAL RAM RATING: DROPDOWN(0-5 and A-D)
// RAM PRIORITY: DROPDOWN(0-5 and A-D)
// RE ASSES RAM RATING: DROPDOWN(0-5 and A-D)